# Generated by Django 4.0 on 2021-12-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LootHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chest_id', models.CharField(max_length=100)),
                ('loot_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('player_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('chests_looted', models.IntegerField(default=0)),
                ('nearby', models.TextField(blank=True, null=True)),
                ('last_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
