# Generated by Django 4.0 on 2021-12-07 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loothistory',
            name='reset_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerdata',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
