# Generated by Django 4.0 on 2021-12-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_loothistory_reset_time_playerdata_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loothistory',
            name='loot_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='loothistory',
            name='reset_time',
            field=models.DateTimeField(),
        ),
    ]
