# Generated by Django 4.0 on 2021-12-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_loothistory_loot_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('marker_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('unreachable', models.BooleanField(default=False)),
                ('_name', models.CharField(max_length=255)),
                ('_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='nearby',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
