# Generated by Django 4.0 on 2021-12-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_marker_alter_playerdata_nearby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='_location',
        ),
        migrations.AddField(
            model_name='marker',
            name='location_x',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='location_y',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
