# Generated by Django 4.0 on 2021-12-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_marker__location_marker_location_x_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='_name',
            new_name='name',
        ),
    ]
