# Generated by Django 4.0 on 2021-12-08 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename__name_marker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loothistory',
            name='chest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.marker'),
        ),
    ]
