# Generated by Django 4.0 on 2021-12-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_playerdata_current_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loothistory',
            old_name='chest_id',
            new_name='chest',
        ),
    ]
