# Generated by Django 4.0 on 2021-12-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_chest_id_loothistory_chest'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
