# Generated by Django 4.0 on 2021-12-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_marker_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='is_elite',
            field=models.BooleanField(default=False),
        ),
    ]
